# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :sit do
    gym(scheme: "LanTuOA", export_method:"development", output_directory: "./build", output_name: "LanTuOA")
    pgyer(api_key: "a8902addd7e0a0a886c42457cf5c4c88", user_key: "f6b9e850fcfa185a2a6d90765d779448", update_description: "测试版本", install_type: "2")
  end
end
